import { ROUTES } from './routes'

export const DRAWERS = {
    DEVICE_STATUS: {
        ID: ROUTES.DEVICE_STATUS.ID,
        PATH: ROUTES.DEVICE_STATUS.PATH,
        NAME: ROUTES.DEVICE_STATUS.NAME
    },
    DEVICE_LIST: {
        ID: ROUTES.DEVICE_LIST.ID,
        PATH: ROUTES.DEVICE_LIST.PATH,
        NAME: ROUTES.DEVICE_LIST.NAME
    },
    DEVICE_ACTIVITY: {
        ID: ROUTES.DEVICE_ACTIVITY.ID,
        PATH: ROUTES.DEVICE_ACTIVITY.PATH,
        NAME: ROUTES.DEVICE_ACTIVITY.NAME
    },
    ALERT_HISTORY: {
        ID: ROUTES.ALERT_HISTORY.ID,
        PATH: ROUTES.ALERT_HISTORY.PATH,
        NAME: ROUTES.ALERT_HISTORY.NAME
    },
    CONTRACT_LIST: {
        ID: ROUTES.CONTRACT_LIST.ID,
        PATH: ROUTES.CONTRACT_LIST.PATH,
        NAME: ROUTES.CONTRACT_LIST.NAME
    },
    ACCOUNT_LIST: {
        ID: ROUTES.ACCOUNT_LIST.ID,
        PATH: ROUTES.ACCOUNT_LIST.PATH,
        NAME: ROUTES.ACCOUNT_LIST.NAME
    },
    ACCOUNT_LOG: {
        ID: ROUTES.ACCOUNT_LOG.ID,
        PATH: ROUTES.ACCOUNT_LOG.PATH,
        NAME: ROUTES.ACCOUNT_LOG.NAME
    },
}